#
#Thu Apr 30 15:57:25 GMT-05:00 2026
acceptInsecureCerts=true
browserName=chrome
goog\:chromeOptions={args\=[start-maximized, test-type, ignore-certificate-errors, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, start-maximized, test-type, ignore-certificate-errors, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins\=*], extensions\=[]}
